name: deploy-client
on:
    push:
        branches: 
            - main 
        paths: 
            - 'client/**'
jobs: 
    build:
        runs-on: ubuntu-latest 
        steps: 
            - uses: actions/checkout@v2 
            - run: cd client && docker build -t karimmofta7/client .
            - 
              uses: docker/login-action@v1 
              with: 
                 username: ${{ secrets.DOCKER_USERNAME }}
                 password: ${{ secrets.DOCKER_TOKEN }} 
            - run: docker push karimmofta7/client
            - uses: digitalocean/action-doctl@v2
              with: 
                token:  ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 
            - run: doctl kubernetes cluster kubeconfig save ticketing
            - run: kubectl rollout restart deployment client-depl
